### ISSUE TITLE
Add support of "dead time" label

### ISSUE THREAD

**Issue by JulienSambre** [didfet/logstash-forwarder-java#18]
Hello,

I have an issue with deleted file. Due to log rollback (like log4j rollback), some files a deleted (with linux mv) but are always open (lsof tag them as "deleted"). The problem is that i have a "too many open file" error from logstash forwarder when the number of open file reach the system max open file (ulimit -n).

logstash forwarder (elastic branch) has create a field in order to solve this problem : dead time (https://discuss.elastic.co/t/too-many-open-files/29969 for example).

I tried this option but got an error (field unknown).

Is there an existing way to solve this problem or could you add the filed "dead time" like in logstash forwarder java?

Thanks!

**Comment by didfet** [comment]
Hi,

I've added the dead time parameter. You can test the latest commit.
